touch .env
chmod 777 .env
echo "POSTGRES_DB=$POSTGRES_DB" > .env
echo "POSTGRES_USER=$POSTGRES_USER" >> .env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
echo "APP__SELFURL=$APP__SELFURL" >> .env
echo "APP__CLIENTURL=$APP__CLIENTURL" >> .env
echo "APP__CORSORIGINS=$APP__CORSORIGINS" >> .env
echo "AUTHSERVER__AUTHORITY=$AUTHSERVER__AUTHORITY" >> .env
echo "AUTHSERVER__SWAGGERCLIENTID=$AUTHSERVER__SWAGGERCLIENTID" >> .env
echo "ALLOWEDHOSTS=$ALLOWEDHOSTS" >> .env
echo "EMAILSETTINGS__SMTPSERVER=$EMAILSETTINGS__SMTPSERVER" >> .env
echo "EMAILSETTINGS__PORT=$EMAILSETTINGS__PORT" >> .env
echo "EMAILSETTINGS__USERNAME=$EMAILSETTINGS__USERNAME" >> .env
echo "EMAILSETTINGS__PASSWORD=$EMAILSETTINGS__PASSWORD" >> .env
echo "EMAILSETTINGS__FROMADDRESS=$EMAILSETTINGS__FROMADDRESS" >> .env
echo "MYAPPCERTIFICATE__X590=$MYAPPCERTIFICATE__X590" >> .env
echo "JWT__KEY=$JWT__KEY" >> .env
echo "JWT__ISSUER=$JWT__ISSUER" >> .env
echo "JWT__AUDIENCE=$JWT__AUDIENCE" >> .env
echo "AUTH0__DOMAIN=$AUTH0__DOMAIN" >> .env
echo "ADMINCREDENTIALS__EMAIL=$ADMINCREDENTIALS__EMAIL" >> .env
echo "ADMINCREDENTIALS__PASSWORD=$ADMINCREDENTIALS__PASSWORD" >> .env
echo "BACKEND_IMAGE_TAG=$BACKEND_IMAGE_TAG" >> .env


sudo docker compose pull
sudo docker compose down --volumes
sudo docker compose up -d
sudo docker image prune -a --force