name: "Deploy dotnet backend using docker on azure vm"
on:
  push:
    branches: ["dev"]
env:
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  APP__CORSORIGINS: ${{ secrets.APP__CORSORIGINS }}
  BACKEND_IMAGE_TAG: ${{ github.sha }}
  APP__SELFURL: ${{ secrets.APP__SELFURL }}
  APP__CLIENTURL: ${{ secrets.APP__CLIENTURL }}
  AUTHSERVER__AUTHORITY: ${{ secrets.AUTHSERVER__AUTHORITY }}
  AUTHSERVER__SWAGGERCLIENTID: ${{ secrets.AUTHSERVER__SWAGGERCLIENTID }}
  ALLOWEDHOSTS: ${{ secrets.ALLOWEDHOSTS }}
  EMAILSETTINGS__SMTPSERVER: ${{ secrets.EMAILSETTINGS__SMTPSERVER }}
  EMAILSETTINGS__PORT: ${{ secrets.EMAILSETTINGS__PORT }}
  EMAILSETTINGS__USERNAME: ${{ secrets.EMAILSETTINGS__USERNAME }}
  EMAILSETTINGS__PASSWORD: ${{ secrets.EMAILSETTINGS__PASSWORD }}
  EMAILSETTINGS__FROMADDRESS: ${{ secrets.EMAILSETTINGS__FROMADDRESS }}
  MYAPPCERTIFICATE__X590: ${{ secrets.MYAPPCERTIFICATE__X590 }}
  JWT__KEY: ${{ secrets.JWT__KEY }}
  JWT__ISSUER: ${{ secrets.JWT__ISSUER }}
  JWT__AUDIENCE: ${{ secrets.JWT__AUDIENCE }}
  AUTH0__DOMAIN: ${{ secrets.AUTH0__DOMAIN }}
  ADMINCREDENTIALS__EMAIL: ${{secrets.ADMINCREDENTIALS__EMAIL}}
  ADMINCREDENTIALS__PASSWORD: ${{secrets.ADMINCREDENTIALS__PASSWORD}}

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Github Checkout"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build and push Docker image"
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

      - name: "SCP to azure vm"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml, init.sql, deploy.sh"
          target: "~/csp-dotnet-compose/"

      - name: "SSH to azure vm"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: POSTGRES_DB, POSTGRES_PASSWORD, POSTGRES_USER, BACKEND_IMAGE_TAG, APP__CORSORIGINS, APP__SELFURL, APP__CLIENTURL, AUTHSERVER__AUTHORITY, AUTHSERVER__SWAGGERCLIENTID, ALLOWEDHOSTS, EMAILSETTINGS__SMTPSERVER, EMAILSETTINGS__PORT, EMAILSETTINGS__USERNAME, EMAILSETTINGS__PASSWORD, EMAILSETTINGS__FROMADDRESS, MYAPPCERTIFICATE__X590, JWT__KEY, JWT__ISSUER, JWT__AUDIENCE, AUTH0__DOMAIN, ADMINCREDENTIALS__EMAIL, ADMINCREDENTIALS__PASSWORD
          script: |
            cd ~/csp-dotnet-compose
            sudo chmod +x deploy.sh
            ./deploy.sh
